version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=accountant
      - DB_USERNAME=accountant
      - DB_PASSWORD=Accountant
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Accountant
      MYSQL_DATABASE: accountant
      MYSQL_USER: accountant
      MYSQL_PASSWORD: Accountant
    ports:
      - "3305:3306"
    networks:
      - laravel_network
    volumes:
      - mysql_accountant:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  mysql_accountant:
